/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
package org.codefeedr.plugins.github.requests

/**
  * Represents a response generated by a request to the GitHub API.
  * @param body the body of the response.
  * @param status the status of the response.
  * @param headers the headers of the response.
  */
case class GitHubResponse(body: String, status: Int, headers: List[Header])

/**
  * Represents a header.
  * @param key the header key.
  * @param value the header values.
  */
case class Header(key: String, value: Array[String])
